---
title: "Netflix"
author: "快樂RRRRR"
date: "2022/05/19"
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'markup', comment = '#>', error = TRUE)
```

### 從 TMDB 取得對應的中文劇名

```{r message=FALSE, warning=FALSE}
### library
library(tidyverse)
library(rvest) #read_html html_nodes(), html_text()

### Param & Var
Netflix_df <- read_csv("concatALL.csv") # 讀取檔案
Res <- tibble()
netflix_en_id <- Netflix_df$id %>% unique # 確認戲劇是唯一的
#count = 0

### Main Program
for (i in c(1:length(netflix_en_id))) { # 建議多加 try catch 避免 http error
  movie_id = netflix_en_id[i]
  if ( identical(as.logical(movie_id), NA) == TRUE ) next
  url <- str_c("https://www.themoviedb.org/tv/", movie_id, "?language=zh-TW")
  movie_zh_name <- url %>% read_html() %>% html_nodes("section > div.title.ott_true > h2 > a") %>% html_text()
  T <- tibble(movie_id, movie_zh_name)
  Res <- bind_rows(Res, T)
  random_num <- runif(1, 3, 8)
  Sys.sleep(random_num)
  print(paste(i , netflix_en_id %>% length))
  #print(Res)
}
Res <- Res %>% mutate( id = movie_id ) %>% select(id, movie_zh_name)
Netflix_df_zh <- Netflix_df %>% left_join(Res)
Netflix_df_zh %>% write_csv("Netflix_df_zh-name.csv")

# 87,101(?)可能有問題
# 有些跑NA看我們能不能手動補，抓資料的時候不知道有少數三四個會跑error，就有一些資訊斷掉QQQQ
```
