---
title: "Netflix"
author: "快樂RRRRR"
date: "2022/05/27"
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'markup', comment = '#>', error = TRUE)
options(stringsAsFactors = F)
options(scipen = 999)
```

### 前10名韓劇之戲劇分類

```{r message=FALSE, warning=FALSE}
### library
library(tidyverse)
library(rvest) #read_html html_nodes(), html_text()
library(jsonlite)
library(stringr)
th <- 
  theme(title = element_text(family="Heiti TC Light"),
        text = element_text(family="Heiti TC Light"), 
        axis.text.y = element_text(family="Heiti TC Light"),
        axis.text.x = element_text(family="Heiti TC Light"),
        legend.text = element_text(family="Heiti TC Light"),
        plot.title = element_text(family="Heiti TC Light")
        )
### Read CSV
Netflix_ratescore <- read_csv("Netflix_ratescore0526.csv") # 讀取檔案

###filter for Korea drama only
korea_drama <- Netflix_ratescore %>% 
  filter(origin_country == "KR")
  
### category ratio
## separate by str_split_fixed, delete 18
korea_drama_category <-  korea_drama %>% 
mutate(genre_ids= str_replace_all(genre_ids, "18", ""))
korea_drama_category[c('genre1', 'genre2', 'genre3', 'genre4')] <- str_split_fixed(korea_drama_category$genre_ids, ',', 4)
korea_drama_category[c('genre1', 'genre2', 'genre3', 'genre4')] <- str_split_fixed(korea_drama_category$genre_ids, ', ', 4)


## A01:get main category of every drama(最主要的)
korea_drama_category <- 
korea_drama_category %>% 
  select(Year, Week, movie_zh_name, Ranking, genre1, genre2, genre3, genre4) %>% 
  mutate(main_category= ifelse(genre1=="", genre2, genre1),
         main_category= ifelse(main_category== "", "18", main_category),  #18
         main_category= str_replace_all(main_category, "10765,\n,\n9648,\n10759", "10765"),  #10765
         main_category= str_replace_all(main_category, "107599648", "10759"),  #10759
         main_category= str_replace_all(main_category, "80,,9648", "80"), #80
         main_category= str_replace_all(main_category, "35", "喜劇"),  #35
         main_category= str_replace_all(main_category, "10759", "動作冒險"), #19759
         main_category= str_replace_all(main_category, "18", "劇情"),  #18
         main_category= str_replace_all(main_category, "10765", "科幻"),  #10765
         main_category= str_replace_all(main_category, "80", "犯罪"),  #80
         main_category= str_replace_all(main_category, "9648", "懸疑"),  #9648
         main_category= str_replace_all(main_category, "10764", "實境"))    #10764
   
  ## ggplot main category
korea_drama_category %>% 
  count(main_category) %>% 
  ggplot(aes(x=reorder(main_category, n), y=n))+
  geom_col(stat="identity",fill="#7EB5D6")+
  geom_text(aes(label = n), colour = "#274257")+
  coord_flip()+
  th+
  labs(title= "每周前10名韓劇主要戲劇分類",
       subtitle= "時間統計自2020年8月10日至2022年4月17日",
    x= element_blank(),
    y= "韓劇部數")
  

## A02: main drama category of every half year
korea_drama_category_time <- 
  korea_drama_category %>% 
  mutate(timeofyear= as.numeric(str_c(Year, Week))) %>% 
  select(-genre1, -genre2, -genre3, -genre4) 

  #need more elegant way...
korea_drama_category_time$timeofyear[1:85 ] <- "2020下半年"
korea_drama_category_time$timeofyear[86:203 ] <- "2021上半年"
korea_drama_category_time$timeofyear[204:346 ] <- "2021下半年"
korea_drama_category_time$timeofyear[347:nrow(korea_drama_category_time) ] <- "2022上半年"

korea_drama_category_time <- 
  korea_drama_category_time %>% 
  group_by(timeofyear) %>%
  mutate(total= n()) %>%
  ungroup() %>%
  group_by(timeofyear, main_category) %>%
  mutate(dramanum= n(),
         percent= round(dramanum/total,2))       #percentage of every category by timeofyear

  

  ##ggplot for every half year
korea_drama_category_time %>% 
  group_by(timeofyear, main_category) %>% 
  summarise(dramanum= n()) %>% 
  ggplot(aes(x=timeofyear, y=dramanum, fill=main_category))+
    geom_col(stat= "identity", position = 'fill')+
    scale_fill_manual(values=c("#7EB5D6", "#2A75A9", "#274257", "#DFC184", "#8F6048", "#b6ac99", "#d9713b"))+
    #scale_y_discrete(limit=c("0%", "25%", "50%","75%",  "100%"))+
  #scale_x_discrete(limit=c("0.00" = "0%", "0.25" = "25%", "0.50"="50%", "0.75"="75%","1.00" = "100%"))+
    #geom_text(aes(label = dramanum), size = 3, hjust = 0.5, vjust = 3, position ="stack", colour= "white") +
    coord_flip()+
    theme(legend.title=element_blank())+
    th+
    labs(title= "疫情期間上榜韓劇之戲劇分類",
         subtitle= "時間統計自2020年8月10日至2022年4月17日",
    x= element_blank(),
    y="各戲劇分類比例")


```

### 剎那花火或經久不衰-持續熱度

```{r}
### clean data- get first place and total ranking times
first_place_times_df <- korea_drama %>% 
  select(Year, Week, Ranking, movie_zh_name) %>% 
  filter(Ranking== 1) %>% 
  count(movie_zh_name) %>% 
  rename(first_place_times= n)


ranking_times_df <- korea_drama %>% 
  count(movie_zh_name) %>% 
  arrange(desc(n)) %>% 
  rename(ranking_times = n)


joined_rankingtimes <- 
ranking_times_df %>% left_join(first_place_times_df) %>% 
  mutate(first_place_times= replace_na(first_place_times, 0),
         minus= ranking_times-first_place_times) 


### B01:ggplot_barplot_times
joined_rankingtimes %>% 
  pivot_longer(cols = c(minus, first_place_times),
    names_to = "type",
    values_to = "times") %>% 
  
  ggplot(aes(x=reorder(movie_zh_name,times), y=times, fill= type))+
  geom_col(stat='identity')+
  scale_fill_manual(labels = c("該周為第1名次數", "該周為2-9名次數"),
                    values = c("#DFC184", "#7EB5D6"))+
  coord_flip()+
  theme(legend.title=element_blank())+
  th+
  labs(title= "曾上榜韓劇之上榜次數",
       subtitle= "時間統計自2020年8月10日至2022年4月17日",
    y= "韓劇上榜次數",
    x="韓劇名稱")
  

### B02:ggplot_line plot by weeks: take drama with the top 10 most times
top5drama <- ranking_times_df %>% 
  slice(1:5) %>%             #according to ranking_time
  select(movie_zh_name) %>% unlist()
  
korea_drama %>% 
  select(Year, Week, Ranking, movie_zh_name) %>% 
  filter(movie_zh_name %in% top5drama) %>% 
  group_by(movie_zh_name) %>% 
  mutate(weeknum= row_number()) %>%         #最多周是「黑道律師」48周
  ## ggplot
  ggplot()+
  aes(x= weeknum, y= fct_rev(factor(Ranking)), group= movie_zh_name, colour= movie_zh_name)+
  geom_line()+
  geom_point()+
  scale_color_manual(values=c("#7EB5D6", "#2A75A9", "#DFC184", "#8F6048", "#b6ac99"))+
  theme(legend.title=element_blank())+
  th+
  labs(title= "在Netflix榜單上最久Top 5韓劇與其名次變化",
       subtitle= "上榜時間最長韓劇為「黑道律師文森佐」共48周",
    y= "榜上名次",
    x="上榜周次")





```

### 叫好（使用IMDB評分）叫座（每週名次）

```{r}

korea_drama_imdbrank <- 
korea_drama %>% 
  select(Year, movie_zh_name, imdb_score, Ranking) %>% 
  #count(movie_zh_name)   #60 different drama
  group_by(movie_zh_name) %>%
  arrange(Ranking,.by_group=TRUE) %>% 
  slice(seq(1)) 


### C01 x=ranking, y=imdb

korea_drama_imdbrank %>% 
  ggplot()+
  aes(x=fct_rev(factor(Ranking)), y=imdb_score)+
  geom_point(aes(color = factor(Year)), size=2.5, alpha=0.8)+
  annotate('text', 
           x = c(10,9,7,1,4,6,10,1,9), 
           y = c(8.8,5.7,8.7,8.0,8.8,4.0,6.6,7.3,8.7), 
           label = c('機智醫生生活','韓國都市怪談','愛的迫降', '雙甲路邊攤','如蝶翩翩','羽球少年團','地獄公使','Do Do Sol Sol La La Sol','二十五，二十一'), 
           family="Heiti TC Light",
           size=3)+
  #geom_text(aes(label=movie_zh_name), size=2, family="Heiti TC Light")+       #顯示全部劇名
  scale_y_continuous(name="IMDB評分", limits=c(0, 10), breaks=c(0,2,4,6,8,10)) +
  scale_color_manual(name = "韓劇上榜年份", values=c("#2A75A9", "#DFC184","#8F6048"))+
  th+
  labs(title= "叫好又叫座？上榜韓劇排名與IMDB評分關係",
       subtitle= "時間統計自2020年8月10日至2022年4月17日",
    x="該劇於Netflix歷來最佳排名")


### C02 x=imdb, y=ranking (與C01擇一)
korea_drama_imdbrank %>% 
  ggplot()+
  aes(y=fct_rev(factor(Ranking)), x=imdb_score)+
  geom_point(aes(color = factor(Year)), size=3, alpha=0.8)+
  scale_color_manual(name = "韓劇上榜年份", values=c("#2A75A9", "#DFC184","#8F6048"))+
  #geom_text(aes(label=movie_zh_name), size=2, family="Heiti TC Light")+
  scale_x_continuous(name="IMDB評分", limits=c(0, 10), breaks=c(0,2,4,6,8,10)) +
  th+
  labs(title= "叫好又叫座？上榜韓劇排名與IMDB評分關係",
       subtitle= "時間統計自2020年8月10日至2022年4月17日",
    y="該劇於Netflix歷來最佳排名")


### C03 facet grid by year, x=ranking, used for comparing whole with each year
library(gridExtra)

C01 <- 
korea_drama_imdbrank %>% 
  ggplot()+
  aes(x=fct_rev(factor(Ranking)), y=imdb_score)+
  geom_point(aes(color = factor(Year)), size=2.5, alpha=0.8)+
  #geom_text(aes(label=movie_zh_name), size=2, family="Heiti TC Light")+       #顯示全部劇名
  scale_y_continuous(name="IMDB評分", limits=c(4, 10), breaks=c(4,6,8,10)) +
  scale_color_manual(name = "韓劇上榜年份", values=c("#2A75A9", "#DFC184","#8F6048"))+
  th+
  labs(title= "叫好又叫座？上榜韓劇排名與IMDB評分關係",
       subtitle= "時間統計自2020年8月10日至2022年4月17日",
    x="該劇於Netflix歷來最佳排名")

grid <- 
korea_drama_imdbrank %>% 
  ggplot()+
  aes(fct_rev(factor(Ranking)), imdb_score) + 
    geom_point(aes(color= factor(Year))) + 
  scale_color_manual(name = "韓劇上榜年份", values=c("#2A75A9", "#DFC184","#8F6048"))+
      th+
  facet_grid(Year ~ ., space = "free")+
  scale_y_continuous(name="IMDB評分", limits=c(4, 10), breaks=c(4,6,8,10)) +
  xlab("該劇於Netflix歷來最佳排名")+
  ylab("IMDB評分")+
  ggtitle("上榜韓劇排名與IMDB評分關係")

grid.arrange(C01, grid, ncol=2)



### C04 category and rank with facet grid
korea_drama %>% 
  mutate(main_category= korea_drama_category$main_category) %>% 
  select(Year, movie_zh_name, Ranking, main_category, imdb_score) %>% 
  group_by(movie_zh_name) %>%
  arrange(Ranking,.by_group=TRUE) %>% 
  slice(seq(1)) %>% 
  ##ggplot
  ggplot()+
  aes(x=fct_rev(factor(Ranking)), y=imdb_score) + 
  geom_point(aes(color = main_category), size=3, alpha=0.8) + 
  scale_color_manual(name = "戲劇類別", values=c("#7EB5D6", "#2A75A9", "#274257", "#DFC184", "#8F6048", "#b6ac99", "#d9713b"))+
  th+
  facet_grid(Year ~ ., space = "free")+
  scale_y_continuous(name="IMDB評分", limits=c(4, 10), breaks=c(4,6,8,10)) +
  xlab("該劇於Netflix歷來最佳排名")+
  ylab("IMDB評分")+
  ggtitle("上榜韓劇排名、IMDB評分與戲劇類別關係")

```

