---
title: "Netflix"
author: "快樂RRRRR"
date: "2022/06/06"
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'markup', comment = '#>', error = TRUE)
options(stringsAsFactors = F)
options(scipen = 999)
```

### 前10名韓劇之戲劇分類

```{r message=FALSE, warning=FALSE}
### library
library(tidyverse)
library(rvest) #read_html html_nodes(), html_text()
library(jsonlite)
library(stringr)
library(cowplot)
th <- 
  theme(title = element_text(family="Heiti TC Light"),
        text = element_text(family="Heiti TC Light"), 
        axis.text.y = element_text(family="Heiti TC Light"),
        axis.text.x = element_text(family="Heiti TC Light"),
        legend.text = element_text(family="Heiti TC Light"),
        plot.title = element_text(family="Heiti TC Light")
        )
### Read CSV
Netflix_tw <- read_csv("data/Netflix_Taiwan_Ranking.csv") # 讀取檔案

###filter for Korea drama only
korea_drama_tw <- Netflix_tw %>% 
  filter(origin_country == "KR")



```

### AA: category from Netflix, without main category

```{r}
## separate drama source, and drama netflix category
korea_drama_neflixcategory_tw <- 
korea_drama_tw %>% 
  select(movie_zh_name, Year, Week, Ranking, category) %>% 
  mutate(category= str_replace_all(category, "網路漫改", "漫畫改編"),
         fromcomic= ifelse(str_detect(category, "漫畫改編"), "Yes", "No"),
         frombook= ifelse(str_detect(category, "書籍改編"), "Yes", "No")) %>% 
  mutate(source= case_when(fromcomic=="Yes" &  frombook== "No"~ '漫畫改編', 
                           fromcomic=="Yes" &  frombook== "Yes"~ '改編自網路漫畫與書籍',
                           fromcomic=="No" &  frombook== "No"~ '無改編',
                           fromcomic=="No" &  frombook== "Yes"~ '書籍改編'),
         category= str_remove_all(category, "漫畫改編, |, 漫畫改編|書籍改編, |, 書籍改編"),    #以上處理戲劇來源
         category= str_replace_all(category, "競賽實境", "競賽, 實境")  
         )  


korea_drama_neflixcategory_tw[c('genre1', 'genre2', 'genre3', 'genre4', 'genre5')] <- str_split_fixed(korea_drama_neflixcategory_tw$category, ', ', 5)

korea_drama_neflixcategory_tw <- korea_drama_neflixcategory_tw %>% 
  gather(genrenum, genrenetflixcats, genre1:genre5) %>% 
  mutate(genrenetflixcats= ifelse(genrenetflixcats=="", NA, genrenetflixcats)) %>% 
  filter(!is.na(genrenetflixcats)) 


## A01:ggplot Netflix category
korea_drama_neflixcategory_tw %>% 
  select(-fromcomic, -frombook, -source, -Ranking) %>% 
  count(movie_zh_name, genrenetflixcats) %>% 
  count(genrenetflixcats) %>% 
  ggplot(aes(x=reorder(genrenetflixcats, n), y=n))+
  geom_col(stat="identity", fill="#2A75A9")+
  geom_text(aes(label = n), colour = "#d9713b", size=2.5)+
  coord_flip()+
  th+
  labs(title= "Netflix台灣站每週上榜韓劇大熱元素",
         subtitle= "時間統計自2020年8月10日至2022年5月29日",
    x= element_blank(),
    y="韓劇部數")


## A02- heat map every week, by half year, drama category一版
korea_drama_neflixcategory_tw %>%
  mutate(timeofyear= ifelse(Week<= 26, "上半年", "下半年"),
         timeofyear= str_c(Year, timeofyear)) %>%
  mutate(weekseq= ifelse(Week<=26, Week, Week-26)) %>%
  group_by(Year, Week) %>%
  mutate(weekdrama= n()) %>%
  ggplot(aes(x=weekseq, y=weekdrama, fill=genrenetflixcats))+
  geom_col(position='fill')+
  scale_x_continuous(name="周次", breaks=seq(1,27,2)) +
  facet_grid(timeofyear ~ ., space = "free")+
  th+
  labs(title= "上榜韓劇之Netflix戲劇分類(每週韓劇的分類，一部多分類)",
         subtitle= "時間統計自2020年8月10日至2022年5月29日",

    y="各戲劇分類比例")


## A03- heat map-another way二版
th_format <- 
  theme(axis.text = element_text(size=8),
        plot.title = element_text(vjust = 10))


a <- 
korea_drama_neflixcategory_tw %>%
  mutate(timeofyear= ifelse(Week<= 26, "上半年", "下半年"),
         timeofyear= str_c(Year, timeofyear)) %>% 
  filter(timeofyear=="2020下半年") %>% 
    group_by(Year, Week) %>% 
  mutate(weekdrama= n()) %>% 
    ggplot(aes(x=Week, y=weekdrama, fill=genrenetflixcats))+
  geom_col(position='fill')+
  labs(title= "台灣上榜韓劇之Netflix戲劇分類")+
  theme_void() +
  theme(legend.position="none") + 
  th_format+th


b <-  
  korea_drama_neflixcategory_tw %>%
  mutate(timeofyear= ifelse(Week<= 26, "上半年", "下半年"),
         timeofyear= str_c(Year, timeofyear)) %>% 
  filter(timeofyear=="2021上半年") %>% 
    group_by(Year, Week) %>% 
  mutate(weekdrama= n()) %>% 
    ggplot(aes(x=Week, y=weekdrama, fill=genrenetflixcats))+
  geom_col(position='fill')+
  theme_void() +
  theme(legend.position="none") + th_format+th


c <- 
korea_drama_neflixcategory_tw %>%
  mutate(timeofyear= ifelse(Week<= 26, "上半年", "下半年"),
         timeofyear= str_c(Year, timeofyear)) %>% 
  filter(timeofyear=="2021下半年") %>% 
    group_by(Year, Week) %>% 
  mutate(weekdrama= n()) %>% 
    ggplot(aes(x=Week, y=weekdrama, fill=genrenetflixcats))+
  geom_col(position='fill')+
  theme_void() +
  theme(legend.position="none") +
 th_format+th


d <-  
  korea_drama_neflixcategory_tw %>%
  mutate(timeofyear= ifelse(Week<= 26, "上半年", "下半年"),
         timeofyear= str_c(Year, timeofyear)) %>% 
  filter(timeofyear=="2022上半年") %>% 
    group_by(Year, Week) %>% 
  mutate(weekdrama= n()) %>% 
    ggplot(aes(x=Week, y=weekdrama, fill=genrenetflixcats))+
  geom_col(position='fill')+
  theme_void() +
  theme(legend.position="none") +
  th_format+th


plot_grid(a, b, c, d, labels = "",nrow = 4) 


# used for getting unique drama
#distinct(movie_zh_name, .keep_all = TRUE)

```




### 剎那花火或經久不衰-持續熱度

```{r}
### clean data- get first place and total ranking times
first_place_times_df_tw <- korea_drama_tw %>% 
  select(Year, Week, Ranking, movie_zh_name) %>% 
  filter(Ranking== 1) %>% 
  count(movie_zh_name) %>% 
  rename(first_place_times= n)


ranking_times_df_tw <- korea_drama_tw %>% 
  count(movie_zh_name) %>% 
  arrange(desc(n)) %>% 
  rename(ranking_times = n)


joined_rankingtimes_tw <- 
ranking_times_df_tw %>% left_join(first_place_times_df_tw) %>% 
  mutate(first_place_times= replace_na(first_place_times, 0),
         minus= ranking_times-first_place_times) 



```

### 排名總表 字不要疊

```{r, fig.height= 9, fig.width=8}
### B01:ggplot_barplot_times字不要疊
joined_rankingtimes_tw %>% 
  pivot_longer(cols = c(minus, first_place_times),
    names_to = "type",
    values_to = "times") %>%    #ranking_times: 最多次上榜為[機智醫生生活]共26 weeks, [黑道律師]24 weeks
  ggplot(aes(x=reorder(movie_zh_name,times), y=times, fill= type))+
  geom_col(stat='identity')+
  scale_fill_manual(labels = c("該周為第1名次數", "該周為2-9名次數"),
                    values = c("#DFC184", "#7EB5D6"))+
  scale_y_continuous(name="韓劇上榜次數", limits=c(0, 30), breaks=c(0,5,10,15,20,25,30)) +
  coord_flip()+
  theme(legend.title=element_blank())+
  th+
  labs(title= "台灣曾上榜韓劇之上榜次數",
       subtitle= "時間統計自2020年8月10日至2022年5月29日",
    #y= "韓劇上榜次數",
    x="韓劇名稱")
```

### 個案劇名次變化top5

```{r}
### B02:ggplot_line plot by weeks: take drama with the top 5 most times
top5drama_tw <- ranking_times_df_tw %>% 
  slice(1:6) %>%             #according to ranking_time
  select(movie_zh_name) %>% unlist()
  
korea_drama_tw %>% 
  select(Year, Week, Ranking, movie_zh_name) %>% 
  filter(movie_zh_name %in% top5drama_tw) %>% 
  group_by(movie_zh_name) %>% 
  mutate(weeknum= row_number()) %>%  
  ## ggplot
  ggplot()+
  aes(x= weeknum, y= fct_rev(factor(Ranking)), group= movie_zh_name, colour= movie_zh_name)+
  geom_line(size=1.5, alpha=0.7)+
  geom_point(size=1.5)+
  scale_color_manual(values=c("#7EB5D6", "#2A75A9", "#DFC184", "#8F6048", "#b6ac99", "#5F9EA0"))+
  scale_x_continuous(name="上榜周次", breaks=seq(0,28,2)) +
  theme(legend.title=element_blank())+
  th+
  labs(title= "在台灣Netflix榜單上最久Top 5韓劇與其名次變化",
       subtitle= "時間統計自2020年8月10日至2022年5月29日\n「二十五二十一」與「驅魔麵館」上榜次數相同並列第五",
    y= "榜上名次")

```



### highlight-改編劇

```{r, fig.height= 9, fig.width=8}
distinct_source <- 
korea_drama_tw %>% 
  distinct(movie_zh_name, .keep_all = T) %>% 
  select(movie_zh_name, category) %>% 
  mutate(category= str_replace_all(category, "網路漫改", "漫畫改編"),
         adapt= ifelse(str_detect(category, "改編"), "Yes", "No")) 



joined_rankingtimes_tw %>% 
  left_join(distinct_source, by="movie_zh_name") %>%   #ranking_times: 最多次上榜為[機智醫生生活]共26 weeks, [黑道律師]24 weeks
  ggplot(aes(x=reorder(movie_zh_name,ranking_times), y=ranking_times, fill=adapt))+
  geom_col(stat='identity')+
  scale_fill_manual(labels = c("非改編劇", "改編劇"),
                    values = c("gray", "tomato"))+
  scale_y_continuous(name="韓劇上榜次數", limits=c(0, 30), breaks=c(0,5,10,15,20,25,30)) +
  coord_flip()+
  theme(legend.title=element_blank())+
  th+
  labs(title= "改編劇受台灣區韓劇市場歡迎",
       subtitle= "包括網路漫畫改編、書籍改編\n時間統計自2020年8月10日至2022年5月29日",
    x="韓劇名稱")



```


